import type { DocumentIR, FragmentDef, SchemaIR, Selection, TypeRef, VarDef } from './parser'

export interface OperationTypes {
  key: string
  result: string
  variables: string
}

export interface CodegenResult {
  operations: OperationTypes[]
  fragments: Map<string, string>
}

const HEADER = `// AUTO-GENERATED by \`yarn graphql:codegen\` — do not edit.
// Source of truth: local-schema.graphql (desktop backend, exported by the
// cargo sdl test) ⊕ extension-schema.graphql (plain-app / plain-nas
// surface). The document corpus is scanned from src/**/*.{ts,vue}.

export type GqlOperationName = keyof GqlOperations

export type GqlResultType<Name extends GqlOperationName> = GqlOperations[Name]['result']

export type GqlVariablesType<Name extends GqlOperationName> = GqlOperations[Name]['variables']
`

interface Ctx {
  schema: SchemaIR
  docFragments: Map<string, FragmentDef>
  emittedFragments: Map<string, string>
}

interface Prop {
  name: string
  type: string
  optional: boolean
}

interface Shape {
  props: Prop[]
  spreads: string[]
  unionBranches: string[]
}

export function generateOperationsSource(
  documents: Array<{ key: string; ir: DocumentIR }>,
  schema: SchemaIR,
): string {
  const fragments = new Map<string, FragmentDef>()
  for (const { ir } of documents) {
    for (const frag of ir.fragments) {
      if (!fragments.has(frag.name)) fragments.set(frag.name, frag)
    }
  }
  const ctx: Ctx = { schema, docFragments: fragments, emittedFragments: new Map() }
  const operations: OperationTypes[] = []
  for (const { key, ir } of documents) {
    const op = ir.operations[0]
    if (!op) continue
    const rootName =
      op.type === 'query'
        ? schema.queryRoot
        : op.type === 'mutation'
          ? schema.mutationRoot
          : schema.subscriptionRoot
    const root = schema.types.get(rootName)
    if (!root) continue
    operations.push({
      key,
      result: shapeToType(buildShape(op.selections, root.name, ctx), 0),
      variables: variablesType(op.variables, ctx),
    })
  }
  const lines: string[] = [HEADER]
  for (const [name, type] of [...ctx.emittedFragments.entries()].sort()) {
    lines.push(`export interface Fragment_${name} ${type}`)
    lines.push('')
  }
  lines.push('export interface GqlOperations {')
  for (const op of operations) {
    lines.push(`  ${op.key}: {`)
    lines.push(`    result: ${indent(op.result)}`)
    lines.push(`    variables: ${indent(op.variables)}`)
    lines.push('  }')
  }
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function variablesType(vars: VarDef[], ctx: Ctx): string {
  if (vars.length === 0) return 'undefined'
  const lines = vars.map((v) => `  ${v.name}: ${tsTypeWithLeaf(v.type, (name) => leafType(name, ctx))}`)
  return `{\n${lines.join('\n')}\n}`
}

function buildShape(selections: Selection[], parentName: string, ctx: Ctx, depth = 0): Shape {
  const shape: Shape = { props: [], spreads: [], unionBranches: [] }
  const isUnionParent = ctx.schema.types.get(parentName)?.kind === 'union'

  for (const sel of selections) {
    if (sel.kind === 'field') {
      const field = ctx.schema.types.get(parentName)?.fields.find((f) => f.name === sel.name)
      if (!field) {
        shape.props.push({ name: sel.alias ?? sel.name, type: 'unknown', optional: true })
        continue
      }
      const leaf = (name: string): string => {
        const nested = sel.selections.length > 0 ? buildShape(sel.selections, name, ctx, depth + 1) : undefined
        if (nested) return shapeToType(nested, depth + 1)
        return leafType(name, ctx)
      }
      shape.props.push({
        name: sel.alias ?? sel.name,
        type: tsTypeWithLeaf(field.type, leaf),
        optional: !field.type.nonNull,
      })
    } else if (sel.kind === 'spread') {
      const frag = ctx.docFragments.get(sel.name)
      if (!frag) continue
      if (!ctx.emittedFragments.has(sel.name)) {
        ctx.emittedFragments.set(sel.name, shapeToType(buildShape(frag.selections, frag.typeCondition, ctx)))
      }
      shape.spreads.push(`Fragment_${sel.name}`)
    } else {
      const cond = sel.typeCondition ?? parentName
      const child = buildShape(sel.selections, cond, ctx, depth)
      if (isUnionParent && sel.typeCondition) {
        shape.unionBranches.push(shapeToType(child, depth))
      } else {
        shape.props.push(...child.props)
        shape.spreads.push(...child.spreads)
      }
    }
  }
  return shape
}

function shapeToType(shape: Shape, depth = 0): string {
  const pad = '  '.repeat(depth + 1)
  const object = shape.props.length
    ? `{\n${shape.props.map((p) => `${pad}${p.name}${p.optional ? '?' : ''}: ${p.type}`).join('\n')}\n${'  '.repeat(depth)}}`
    : ''
  if (shape.unionBranches.length > 0) {
    const variants = [...(object ? [object] : []), ...shape.unionBranches, ...shape.spreads]
    return variants.length === 1 ? variants[0] : variants.join(' | ')
  }
  const parts = [...(object ? [object] : []), ...shape.spreads]
  if (parts.length === 0) return '{}'
  return parts.length === 1 ? parts[0] : parts.join(' & ')
}

function tsTypeWithLeaf(ref: TypeRef, leaf: (name: string) => string): string {
  if (ref.ofType === 'list') return `Array<${tsTypeWithLeaf(ref.inner, leaf)}>`
  return leaf(ref.name)
}

function leafType(name: string, ctx: Ctx): string {
  if (name === 'String' || name === 'ID') return 'string'
  if (name === 'Int' || name === 'Float' || name === 'Long') return 'number'
  if (name === 'Boolean') return 'boolean'
  const def = ctx.schema.types.get(name)
  if (def?.kind === 'enum' && def.enumValues.length > 0) {
    return def.enumValues.map((v) => `'${v}'`).join(' | ')
  }
  return 'unknown'
}

function indent(type: string): string {
  return type.includes('\n') ? type.split('\n').join('\n    ') : type
}
