// AUTO-GENERATED by `yarn graphql:codegen` — do not edit.
// Source of truth: local-schema.graphql (desktop backend, exported by the
// cargo sdl test) ⊕ extension-schema.graphql (plain-app / plain-nas
// surface). The document corpus is scanned from src/**/*.{ts,vue}.

export type GqlOperationName = keyof GqlOperations

export type GqlResultType<Name extends GqlOperationName> = GqlOperations[Name]['result']

export type GqlVariablesType<Name extends GqlOperationName> = GqlOperations[Name]['variables']

export interface Fragment_AppFragment {
  clientId: string
  urlToken: string
  httpPort: number
  httpsPort: number
  appDir: string
  deviceName: string
  deviceType: 'PHONE' | 'TABLET' | 'COMPUTER' | 'TV' | 'NAS' | 'OTHER' | 'UNKNOWN'
  capabilities: Array<'MEDIA_TRASH' | 'MIRROR_AUDIO' | 'DOC_PREVIEW' | 'IMAGE_SEARCH' | 'MEDIA_SCAN' | 'SMS' | 'CALLS' | 'CALL_PHONE' | 'CONTACTS' | 'PACKAGES' | 'NOTES' | 'FEEDS' | 'SCREEN_MIRROR' | 'IMAGE_EDITOR' | 'NOTIFICATIONS' | 'CLIPBOARD' | 'POMODORO' | 'LAN_SHARE' | 'DISK_MANAGER'>
  buildChannel: 'GITHUB' | 'GOOGLE' | 'FDROID'
  permissions: Array<'WRITE_EXTERNAL_STORAGE' | 'READ_SMS' | 'SEND_SMS' | 'READ_CONTACTS' | 'WRITE_CONTACTS' | 'READ_CALL_LOG' | 'WRITE_CALL_LOG' | 'CALL_PHONE' | 'POST_NOTIFICATIONS' | 'NEARBY_WIFI_DEVICES' | 'ACCESS_FINE_LOCATION' | 'CAMERA' | 'SYSTEM_ALERT_WINDOW' | 'RECORD_AUDIO' | 'READ_MEDIA_IMAGES' | 'READ_MEDIA_VIDEOS' | 'READ_MEDIA_AUDIO' | 'NOTIFICATION_LISTENER' | 'READ_PHONE_STATE' | 'READ_PHONE_NUMBERS' | 'SCHEDULE_EXACT_ALARM' | 'QUERY_ALL_PACKAGES' | 'ADB' | 'CLIPBOARD'>
  downloadsDir: string
  developerMode: boolean
  debug: boolean
}

export interface Fragment_AudioFragment {
  id: string
  title: string
  artist: string
  path: string
  durationMs: number
  size: number
  bucketId: string
  albumFileId: string
  createdAt: string
  updatedAt: string
  tags: Array<Fragment_TagSubFragment>
}

export interface Fragment_AudioItemFragment {
  title: string
  artist: string
  path: string
  durationMs: number
}

export interface Fragment_BookmarkFragment {
  id: string
  url: string
  title: string
  faviconPath: string
  groupId: string
  pinned: boolean
  clickCount: number
  lastClickedAt?: string
  sortOrder: number
  createdAt: string
  updatedAt: string
}

export interface Fragment_BookmarkGroupFragment {
  id: string
  name: string
  collapsed: boolean
  sortOrder: number
  itemCount: number
  createdAt: string
  updatedAt: string
}

export interface Fragment_CallFragment {
  id: string
  name: string
  number: string
  durationSec: number
  accountId: string
  startedAt: string
  photoId: string
  type: 'INCOMING' | 'OUTGOING' | 'MISSED' | 'VOICEMAIL' | 'REJECTED' | 'BLOCKED' | 'ANSWERED_EXTERNALLY' | 'UNKNOWN'
  geo?: {
    country: string
    numberType: string
    carrier: string
    description: string
  }
  tags: Array<Fragment_TagSubFragment>
}

export interface Fragment_ChatChannelFragment {
  id: string
  name: string
  ownerId: string
  members: Array<Fragment_ChatChannelMemberFragment>
  version: number
  status: 'JOINED' | 'LEFT' | 'KICKED'
  createdAt: string
  updatedAt: string
}

export interface Fragment_ChatChannelMemberFragment {
  peerId: string
  status: 'JOINED' | 'PENDING'
}

export interface Fragment_ChatItemFragment {
  id: string
  fromId: string
  toId: string
  channelId?: string
  createdAt: string
  content: string
  status: 'SENT' | 'FAILED' | 'PARTIAL' | 'PENDING'
  statusData: string
  data?: {
    ids: Array<string>
  } | {
    ids: Array<string>
  } | {
    linkPreviewImageIds: Array<string>
  }
}

export interface Fragment_ClipboardItemFragment {
  id: string
  text: string
  source: string
  label: string
  sensitive: boolean
  createdAt: string
}

export interface Fragment_ContactFragment {
  id: string
  suffix: string
  prefix: string
  firstName: string
  middleName: string
  lastName: string
  updatedAt: string
  notes: string
  source: string
  thumbnailId: string
  starred: boolean
  phoneNumbers: Array<{
    value: string
    type: 'CUSTOM' | 'HOME' | 'MOBILE' | 'WORK' | 'FAX_WORK' | 'FAX_HOME' | 'PAGER' | 'OTHER' | 'CALLBACK' | 'CAR' | 'COMPANY_MAIN' | 'ISDN' | 'MAIN' | 'OTHER_FAX' | 'RADIO' | 'TELEX' | 'TTY_TDD' | 'WORK_MOBILE' | 'WORK_PAGER' | 'ASSISTANT'
    label: string
    normalizedNumber: string
  }>
  addresses: Array<{
    value: string
    type: 'CUSTOM' | 'HOME' | 'WORK' | 'OTHER'
    label: string
  }>
  emails: Array<{
    value: string
    type: 'CUSTOM' | 'HOME' | 'WORK' | 'OTHER' | 'MOBILE'
    label: string
  }>
  websites: Array<{
    value: string
    type: 'CUSTOM' | 'HOMEPAGE' | 'BLOG' | 'FTP' | 'HOME' | 'WORK' | 'OTHER'
    label: string
  }>
  events: Array<{
    value: string
    type: 'CUSTOM' | 'ANNIVERSARY' | 'BIRTHDAY' | 'OTHER'
    label: string
  }>
  ims: Array<{
    value: string
    protocol: 'CUSTOM' | 'AIM' | 'MSN' | 'YAHOO' | 'SKYPE' | 'QQ' | 'GOOGLE_TALK' | 'ICQ' | 'JABBER' | 'NETMEETING'
    customProtocol: string
  }>
  tags: Array<Fragment_TagSubFragment>
}

export interface Fragment_DeviceInfoFragment {
  name: string
  platform: 'ANDROID' | 'IOS' | 'MACOS' | 'WINDOWS' | 'LINUX'
  manufacturer: string
  model: string
  osName: string
  osVersion: string
  kernelVersion: string
  appVersion: string
  appBuildNumber: string
  language: string
  cpuArch: string
  cpuModel?: string
  totalMemory: number
  totalStorage: number
  display?: {
    width: number
    height: number
    density: number
  }
  android?: {
    sdkVersion: number
    versionCodeName: string
    securityPatch: string
    bootloader: string
    fingerprint: string
    hardware: string
    radioVersion: string
    board: string
    buildBrand: string
    buildNumber: string
    device: string
    javaVmVersion: string
    glEsVersion: string
    buildTime: string
  }
}

export interface Fragment_DeviceStatusFragment {
  uptimeSec: number
  batteryLevel?: number
  charging: boolean
  temperatures: Array<{
    label: string
    celsius: number
  }>
  cpuUsage: number
  memoryAvailable?: number
  storageAvailable: number
}

export interface Fragment_DocFragment {
  id: string
  title: string
  path: string
  extension: string
  size: number
  bucketId: string
  createdAt: string
  updatedAt: string
  tags: Array<Fragment_TagSubFragment>
}

export interface Fragment_FeedEntryFragment {
  id: string
  title: string
  url: string
  image: string
  author: string
  description: string
  content: string
  feedId: string
  rawId: string
  publishedAt: string
  createdAt: string
  updatedAt: string
  tags: Array<Fragment_TagSubFragment>
}

export interface Fragment_FeedFragment {
  id: string
  name: string
  url: string
  fetchContent: boolean
  createdAt: string
  updatedAt: string
}

export interface Fragment_FileFragment {
  path: string
  isDir: boolean
  createdAt?: string
  updatedAt: string
  size: number
  childCount: number
  mediaId?: string
}

export interface Fragment_ImageFragment {
  id: string
  title: string
  path: string
  size: number
  bucketId: string
  takenAt?: string
  createdAt: string
  updatedAt: string
  tags: Array<Fragment_TagSubFragment>
}

export interface Fragment_NoteFragment {
  id: string
  title: string
  content: string
  deletedAt?: string
  createdAt: string
  updatedAt: string
  tags: Array<Fragment_TagSubFragment>
}

export interface Fragment_NotificationFragment {
  id: string
  onlyOnce: boolean
  isClearable: boolean
  appId: string
  appName: string
  postedAt: string
  silent: boolean
  title: string
  body: string
  actions: Array<string>
  replyActions: Array<string>
}

export interface Fragment_PackageFragment {
  id: string
  name: string
  type: 'SYSTEM' | 'USER'
  version: string
  path: string
  size: number
  certs: Array<{
    issuer: string
    subject: string
    serialNumber: string
    validFrom: string
    validTo: string
  }>
  installedAt: string
  updatedAt: string
}

export interface Fragment_SmsConversationFragment {
  id: string
  address: string
  snippet: string
  lastMessageAt: string
  messageCount: number
  read: boolean
}

export interface Fragment_SmsConversationWithAddressesFragment {
  id: string
  address: string
  addresses: Array<string>
  snippet: string
  lastMessageAt: string
  messageCount: number
  read: boolean
}

export interface Fragment_SmsFragment {
  id: string
  body: string
  address: string
  serviceCenter: string
  sentAt: string
  type: 'INBOX' | 'SENT' | 'DRAFT' | 'OUTBOX' | 'FAILED' | 'QUEUED' | 'UNKNOWN'
  threadId: string
  subscriptionId: number
  isMms: boolean
  attachments: Array<{
    path: string
    contentType: string
    name: string
  }>
  tags: Array<Fragment_TagSubFragment>
}

export interface Fragment_TagFragment {
  id: string
  name: string
  count: number
}

export interface Fragment_TagSubFragment {
  id: string
  name: string
}

export interface Fragment_VideoFragment {
  id: string
  title: string
  path: string
  durationMs: number
  size: number
  bucketId: string
  createdAt: string
  updatedAt: string
  takenAt?: string
  tags: Array<Fragment_TagSubFragment>
}

export interface GqlOperations {
  allContactsGQL: {
    result: {
      contacts: Array<Fragment_ContactFragment>
    }
    variables: undefined
  }
  sharedInfoGQL: {
    result: {
      sharedInfo: {
        name: string
        readOnly: boolean
        requiresPassword: boolean
        expiresAt?: string
        urlToken: string
        entries: Array<{
          name: string
          virtualPath: string
          isDir: boolean
          size: number
          mimeType: string
          hasThumb: boolean
        }>
      }
    }
    variables: {
      virtualPath: string
    }
  }
  clearAppLogsGQL: {
    result: {
      clearAppLogs: boolean
    }
    variables: undefined
  }
  updateDeviceNameGQL: {
    result: {
      updateDeviceName: boolean
    }
    variables: {
      name: string
    }
  }
  sendChatItemGQL: {
    result: {
      sendChatItem: Array<Fragment_ChatItemFragment>
    }
    variables: {
      target: string
      content: string
    }
  }
  deleteChatItemGQL: {
    result: {
      deleteChatItem: boolean
    }
    variables: {
      id: string
    }
  }
  deleteChatItemsGQL: {
    result: {
      deleteChatItems: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  retryChatItemGQL: {
    result: {
      retryChatItem: Fragment_ChatItemFragment
    }
    variables: {
      id: string
    }
  }
  createChatChannelGQL: {
    result: {
      createChatChannel: Fragment_ChatChannelFragment
    }
    variables: {
      name: string
    }
  }
  updateChatChannelGQL: {
    result: {
      updateChatChannel: Fragment_ChatChannelFragment
    }
    variables: {
      id: string
      name: string
    }
  }
  deleteChatChannelGQL: {
    result: {
      deleteChatChannel: boolean
    }
    variables: {
      id: string
    }
  }
  deletePeerGQL: {
    result: {
      deletePeer: boolean
    }
    variables: {
      id: string
    }
  }
  unpairPeerGQL: {
    result: {
      unpairPeer: boolean
    }
    variables: {
      id: string
    }
  }
  leaveChatChannelGQL: {
    result: {
      leaveChatChannel: boolean
    }
    variables: {
      id: string
    }
  }
  addChatChannelMemberGQL: {
    result: {
      addChatChannelMember: Fragment_ChatChannelFragment
    }
    variables: {
      id: string
      peerId: string
    }
  }
  removeChatChannelMemberGQL: {
    result: {
      removeChatChannelMember: Fragment_ChatChannelFragment
    }
    variables: {
      id: string
      peerId: string
    }
  }
  acceptChatChannelInviteGQL: {
    result: {
      acceptChatChannelInvite: boolean
    }
    variables: {
      id: string
    }
  }
  respondChannelInviteGQL: {
    result: {
      respondChannelInvite: boolean
    }
    variables: {
      id: string
      accept: boolean
    }
  }
  declineChatChannelInviteGQL: {
    result: {
      declineChatChannelInvite: boolean
    }
    variables: {
      id: string
    }
  }
  createDirGQL: {
    result: {
      createDir: Fragment_FileFragment
    }
    variables: {
      path: string
    }
  }
  writeTextFileGQL: {
    result: {
      writeTextFile: Fragment_FileFragment
    }
    variables: {
      path: string
      content: string
      overwrite: boolean
    }
  }
  renameFileGQL: {
    result: {
      renameFile: boolean
    }
    variables: {
      path: string
      name: string
    }
  }
  copyFileGQL: {
    result: {
      copyFile: boolean
    }
    variables: {
      src: string
      dst: string
      overwrite: boolean
    }
  }
  moveFileGQL: {
    result: {
      moveFile: boolean
    }
    variables: {
      src: string
      dst: string
      overwrite: boolean
    }
  }
  playAudioGQL: {
    result: {
      playAudio: Fragment_AudioItemFragment
    }
    variables: {
      path: string
    }
  }
  updateAudioPlayModeGQL: {
    result: {
      updateAudioPlayMode: boolean
    }
    variables: {
      mode: 'REPEAT' | 'REPEAT_ONE' | 'SHUFFLE'
    }
  }
  removeAudioFromQueueGQL: {
    result: {
      removeAudioFromQueue: boolean
    }
    variables: {
      path: string
    }
  }
  addAudiosToQueueGQL: {
    result: {
      addAudiosToQueue: boolean
    }
    variables: {
      query: string
    }
  }
  clearAudioQueueGQL: {
    result: {
      clearAudioQueue: boolean
    }
    variables: undefined
  }
  reorderAudioQueueGQL: {
    result: {
      reorderAudioQueue: boolean
    }
    variables: {
      paths: Array<string>
    }
  }
  deleteMediaItemsGQL: {
    result: {
      deleteMediaItems: {
        affectedCount: number
      }
    }
    variables: {
      type: 'AUDIO' | 'VIDEO' | 'IMAGE' | 'DOC'
      query: string
    }
  }
  trashMediaItemsGQL: {
    result: {
      trashMediaItems: {
        affectedCount: number
      }
    }
    variables: {
      type: 'AUDIO' | 'VIDEO' | 'IMAGE' | 'DOC'
      query: string
    }
  }
  restoreMediaItemsGQL: {
    result: {
      restoreMediaItems: {
        affectedCount: number
      }
    }
    variables: {
      type: 'AUDIO' | 'VIDEO' | 'IMAGE' | 'DOC'
      query: string
    }
  }
  moveMediaItemsGQL: {
    result: {
      moveMediaItems: {
        affectedCount: number
      }
    }
    variables: {
      type: 'AUDIO' | 'VIDEO' | 'IMAGE' | 'DOC'
      query: string
      destDir: string
    }
  }
  trashSmsGQL: {
    result: {
      trashSms: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  restoreSmsGQL: {
    result: {
      restoreSms: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  deleteSmsGQL: {
    result: {
      deleteSms: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  removeFromTagsGQL: {
    result: {
      removeFromTags: boolean
    }
    variables: {
      type: 'DEFAULT' | 'AUDIO' | 'VIDEO' | 'IMAGE' | 'SMS' | 'CONTACT' | 'NOTE' | 'FEED_ENTRY' | 'CALL' | 'PACKAGE' | 'FILE' | 'APP_FILE' | 'DOC'
      tagIds: Array<string>
      query: string
    }
  }
  addToTagsGQL: {
    result: {
      addToTags: boolean
    }
    variables: {
      type: 'DEFAULT' | 'AUDIO' | 'VIDEO' | 'IMAGE' | 'SMS' | 'CONTACT' | 'NOTE' | 'FEED_ENTRY' | 'CALL' | 'PACKAGE' | 'FILE' | 'APP_FILE' | 'DOC'
      tagIds: Array<string>
      query: string
    }
  }
  updateTagRelationsGQL: {
    result: {
      updateTagRelations: boolean
    }
    variables: {
      type: 'DEFAULT' | 'AUDIO' | 'VIDEO' | 'IMAGE' | 'SMS' | 'CONTACT' | 'NOTE' | 'FEED_ENTRY' | 'CALL' | 'PACKAGE' | 'FILE' | 'APP_FILE' | 'DOC'
      item: unknown
      addTagIds: Array<string>
      removeTagIds: Array<string>
    }
  }
  createTagGQL: {
    result: {
      createTag: Fragment_TagFragment
    }
    variables: {
      type: 'DEFAULT' | 'AUDIO' | 'VIDEO' | 'IMAGE' | 'SMS' | 'CONTACT' | 'NOTE' | 'FEED_ENTRY' | 'CALL' | 'PACKAGE' | 'FILE' | 'APP_FILE' | 'DOC'
      name: string
    }
  }
  updateTagGQL: {
    result: {
      updateTag: Fragment_TagFragment
    }
    variables: {
      id: string
      name: string
    }
  }
  deleteTagGQL: {
    result: {
      deleteTag: boolean
    }
    variables: {
      id: string
    }
  }
  addFavoriteFolderGQL: {
    result: {
      addFavoriteFolder: Array<{
        rootPath: string
        fullPath: string
      }>
    }
    variables: {
      rootPath: string
      fullPath: string
    }
  }
  removeFavoriteFolderGQL: {
    result: {
      removeFavoriteFolder: Array<{
        rootPath: string
        fullPath: string
        alias?: string
      }>
    }
    variables: {
      fullPath: string
    }
  }
  setFavoriteFolderAliasGQL: {
    result: {
      setFavoriteFolderAlias: Array<{
        rootPath: string
        fullPath: string
        alias?: string
      }>
    }
    variables: {
      fullPath: string
      alias: string
    }
  }
  createNoteGQL: {
    result: {
      createNote: Fragment_NoteFragment
    }
    variables: {
      input: unknown
    }
  }
  updateNoteGQL: {
    result: {
      updateNote: Fragment_NoteFragment
    }
    variables: {
      id: string
      input: unknown
    }
  }
  deleteNotesGQL: {
    result: {
      deleteNotes: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  trashNotesGQL: {
    result: {
      trashNotes: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  restoreNotesGQL: {
    result: {
      restoreNotes: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  deleteFeedEntriesGQL: {
    result: {
      deleteFeedEntries: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  deleteCallsGQL: {
    result: {
      deleteCalls: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  deleteContactsGQL: {
    result: {
      deleteContacts: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  createFeedGQL: {
    result: {
      createFeed: Fragment_FeedFragment
    }
    variables: {
      url: string
      fetchContent: boolean
    }
  }
  importFeedsGQL: {
    result: {
      importFeeds: boolean
    }
    variables: {
      content: string
    }
  }
  exportFeedsGQL: {
    result: {
      exportFeeds: string
    }
    variables: undefined
  }
  exportNotesGQL: {
    result: {
      exportNotes: string
    }
    variables: {
      query: string
    }
  }
  relaunchAppGQL: {
    result: {
      relaunchApp: boolean
    }
    variables: undefined
  }
  openAccessibilitySettingsGQL: {
    result: {
      openAccessibilitySettings: boolean
    }
    variables: undefined
  }
  openWebSettingsGQL: {
    result: {
      openWebSettings: boolean
    }
    variables: {
      feature: 'FILES' | 'CONTACTS' | 'SMS' | 'CALL_LOGS' | 'CALL_PHONE' | 'PHONE_NUMBER' | 'APPS' | 'NOTIFICATIONS' | 'CLIPBOARD'
    }
  }
  deleteFeedGQL: {
    result: {
      deleteFeed: boolean
    }
    variables: {
      id: string
    }
  }
  updateFeedGQL: {
    result: {
      updateFeed: Fragment_FeedFragment
    }
    variables: {
      id: string
      name: string
      fetchContent: boolean
    }
  }
  syncFeedsGQL: {
    result: {
      syncFeeds: boolean
    }
    variables: {
      id: string
    }
  }
  syncFeedEntryContentGQL: {
    result: {
      syncFeedEntryContent: {
        feed?: Fragment_FeedFragment
      } & Fragment_FeedEntryFragment
    }
    variables: {
      id: string
    }
  }
  callGQL: {
    result: {
      call: boolean
    }
    variables: {
      number: string
      showDialer: boolean
    }
  }
  setClipboardGQL: {
    result: {
      setClipboard: boolean
    }
    variables: {
      text: string
    }
  }
  sendSmsGQL: {
    result: {
      sendSms: boolean
    }
    variables: {
      number: string
      body: string
      subscriptionId: number
    }
  }
  sendSmsWithRequestIdGQL: {
    result: {
      sendSms: boolean
    }
    variables: {
      number: string
      body: string
      subscriptionId: number
      requestId: string
    }
  }
  archiveSmsConversationGQL: {
    result: {
      archiveSmsConversation: boolean
    }
    variables: {
      id: string
    }
  }
  unarchiveSmsConversationGQL: {
    result: {
      unarchiveSmsConversation: boolean
    }
    variables: {
      id: string
    }
  }
  sendMmsGQL: {
    result: {
      sendMms: string
    }
    variables: {
      number: string
      body: string
      attachmentPaths: Array<string>
      threadId: string
    }
  }
  uninstallPackagesGQL: {
    result: {
      uninstallPackages: boolean
    }
    variables: {
      ids: Array<string>
    }
  }
  uninstallPackageGQL: {
    result: {
      uninstallPackages: boolean
    }
    variables: {
      id: string
    }
  }
  installPackageGQL: {
    result: {
      installPackage: {
        id: string
        updatedAt?: string
        isNew: boolean
      }
    }
    variables: {
      path: string
    }
  }
  startScreenMirrorGQL: {
    result: {
      startScreenMirror: boolean
    }
    variables: {
      audio: boolean
    }
  }
  requestScreenMirrorAudioGQL: {
    result: {
      requestScreenMirrorAudio: boolean
    }
    variables: undefined
  }
  stopScreenMirrorGQL: {
    result: {
      stopScreenMirror: boolean
    }
    variables: undefined
  }
  setTempValueGQL: {
    result: {
      setTempValue: {
        key: string
        value: string
      }
    }
    variables: {
      key: string
      value: string
    }
  }
  deleteNotificationsGQL: {
    result: {
      deleteNotifications: {
        affectedCount: number
      }
    }
    variables: {
      ids: Array<string>
    }
  }
  replyNotificationGQL: {
    result: {
      replyNotification: boolean
    }
    variables: {
      id: string
      actionIndex: number
      text: string
    }
  }
  deleteClipboardItemsGQL: {
    result: {
      deleteClipboardItems: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  updateScreenMirrorQualityGQL: {
    result: {
      updateScreenMirrorQuality: boolean
    }
    variables: {
      mode: 'HD' | 'SMOOTH'
    }
  }
  saveFeedEntriesToNotesGQL: {
    result: {
      saveFeedEntriesToNotes: Array<string>
    }
    variables: {
      query: string
    }
  }
  mergeChunksGQL: {
    result: {
      mergeChunks: {
        status: 'NONE' | 'STARTED' | 'MERGING' | 'DONE' | 'FAILED'
        value?: string
        mergedSize?: number
        error?: string
      }
    }
    variables: {
      fileId: string
      totalChunks: number
      path: string
      replace: boolean
      totalSize: number
    }
  }
  mergeAppFileChunksGQL: {
    result: {
      mergeAppFileChunks: {
        status: 'NONE' | 'STARTED' | 'MERGING' | 'DONE' | 'FAILED'
        value?: string
        mergedSize?: number
        error?: string
      }
    }
    variables: {
      fileId: string
      totalChunks: number
      fileName: string
      totalSize: number
    }
  }
  deleteChunksGQL: {
    result: {
      deleteChunks: boolean
    }
    variables: {
      fileId: string
    }
  }
  startPomodoroGQL: {
    result: {
      startPomodoro: boolean
    }
    variables: {
      durationSec: number
    }
  }
  stopPomodoroGQL: {
    result: {
      stopPomodoro: boolean
    }
    variables: undefined
  }
  pausePomodoroGQL: {
    result: {
      pausePomodoro: boolean
    }
    variables: undefined
  }
  sendScreenMirrorControlGQL: {
    result: {
      sendScreenMirrorControl: boolean
    }
    variables: {
      input: unknown
    }
  }
  addBookmarksGQL: {
    result: {
      addBookmarks: Array<Fragment_BookmarkFragment>
    }
    variables: {
      urls: Array<string>
      groupId: string
    }
  }
  updateBookmarkGQL: {
    result: {
      updateBookmark: Fragment_BookmarkFragment
    }
    variables: {
      id: string
      input: unknown
    }
  }
  deleteBookmarksGQL: {
    result: {
      deleteBookmarks: {
        affectedCount: number
      }
    }
    variables: {
      ids: Array<string>
    }
  }
  recordBookmarkClickGQL: {
    result: {
      recordBookmarkClick: boolean
    }
    variables: {
      id: string
    }
  }
  createBookmarkGroupGQL: {
    result: {
      createBookmarkGroup: Fragment_BookmarkGroupFragment
    }
    variables: {
      name: string
    }
  }
  updateBookmarkGroupGQL: {
    result: {
      updateBookmarkGroup: Fragment_BookmarkGroupFragment
    }
    variables: {
      id: string
      name: string
      collapsed: boolean
      sortOrder: number
    }
  }
  deleteBookmarkGroupGQL: {
    result: {
      deleteBookmarkGroup: boolean
    }
    variables: {
      id: string
    }
  }
  deleteFilesGQL: {
    result: {
      deleteFiles: {
        affectedCount: number
      }
    }
    variables: {
      paths: Array<string>
    }
  }
  enableImageSearchGQL: {
    result: {
      enableImageSearch: boolean
    }
    variables: undefined
  }
  disableImageSearchGQL: {
    result: {
      disableImageSearch: boolean
    }
    variables: undefined
  }
  cancelImageModelDownloadGQL: {
    result: {
      cancelImageModelDownload: boolean
    }
    variables: undefined
  }
  startImageIndexGQL: {
    result: {
      startImageIndex: boolean
    }
    variables: {
      force: boolean
    }
  }
  cancelImageIndexGQL: {
    result: {
      cancelImageIndex: boolean
    }
    variables: undefined
  }
  createContactGQL: {
    result: {
      createContact: Fragment_ContactFragment
    }
    variables: {
      input: unknown
    }
  }
  updateContactGQL: {
    result: {
      updateContact: Fragment_ContactFragment
    }
    variables: {
      id: string
      input: unknown
    }
  }
  deleteContactGQL: {
    result: {
      deleteContacts: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  deleteCallGQL: {
    result: {
      deleteCalls: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  deleteNoteGQL: {
    result: {
      deleteNotes: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  deleteFeedEntryGQL: {
    result: {
      deleteFeedEntries: {
        affectedCount: number
      }
    }
    variables: {
      query: string
    }
  }
  deleteDataStoreEntryGQL: {
    result: {
      deleteDataStoreEntry: boolean
    }
    variables: {
      key: string
    }
  }
  createDbTableRowGQL: {
    result: {
      createDbTableRow: boolean
    }
    variables: {
      table: string
      row: string
    }
  }
  deleteDbTableRowsGQL: {
    result: {
      deleteDbTableRows: boolean
    }
    variables: {
      table: string
      ids: Array<string>
    }
  }
  startDiscoveryGQL: {
    result: {
      startDiscovery: boolean
    }
    variables: undefined
  }
  stopDiscoveryGQL: {
    result: {
      stopDiscovery: boolean
    }
    variables: undefined
  }
  pairDeviceGQL: {
    result: {
      pairDevice: boolean
    }
    variables: {
      input: unknown
    }
  }
  cancelPairingGQL: {
    result: {
      cancelPairing: boolean
    }
    variables: {
      deviceId: string
    }
  }
  respondToPairingGQL: {
    result: {
      respondToPairing: boolean
    }
    variables: {
      input: unknown
      accepted: boolean
    }
  }
  downloadPeerFileGQL: {
    result: {
      downloadPeerFile: boolean
    }
    variables: {
      messageId: string
      peerId: string
    }
  }
  pauseDownloadGQL: {
    result: {
      pauseDownload: boolean
    }
    variables: {
      messageId: string
    }
  }
  resumeDownloadGQL: {
    result: {
      resumeDownload: boolean
    }
    variables: {
      messageId: string
      peerId: string
    }
  }
  retryDownloadGQL: {
    result: {
      retryDownload: boolean
    }
    variables: {
      messageId: string
      peerId: string
    }
  }
  pauseMediaScanGQL: {
    result: {
      pauseMediaScan: boolean
    }
    variables: undefined
  }
  resumeMediaScanGQL: {
    result: {
      resumeMediaScan: boolean
    }
    variables: undefined
  }
  stopMediaScanGQL: {
    result: {
      stopMediaScan: boolean
    }
    variables: undefined
  }
  rebuildMediaIndexGQL: {
    result: {
      rebuildMediaIndex: boolean
    }
    variables: {
      root: string
    }
  }
  formatDiskGQL: {
    result: {
      formatDisk: boolean
    }
    variables: {
      path: string
    }
  }
  setSambaSettingsGQL: {
    result: {
      setSambaSettings: boolean
    }
    variables: {
      input: unknown
    }
  }
  setSambaUserPasswordGQL: {
    result: {
      setSambaUserPassword: boolean
    }
    variables: {
      password: string
    }
  }
  chatItemsGQL: {
    result: {
      chatItems: Array<Fragment_ChatItemFragment>
    }
    variables: {
      target: string
    }
  }
  chatItemGQL: {
    result: {
      chatItem?: Fragment_ChatItemFragment
    }
    variables: {
      id: string
    }
  }
  peersGQL: {
    result: {
      peers: Array<{
        id: string
        name: string
        ip: string
        status: 'PAIRED' | 'UNPAIRED' | 'CHANNEL'
        online: boolean
        port: number
        deviceType: 'PHONE' | 'TABLET' | 'COMPUTER' | 'TV' | 'NAS' | 'OTHER' | 'UNKNOWN'
        createdAt: string
        updatedAt: string
      }>
    }
    variables: undefined
  }
  latestChatItemsGQL: {
    result: {
      latestChatItems: Array<Fragment_ChatItemFragment>
    }
    variables: undefined
  }
  appFilesGQL: {
    result: {
      appFiles: Array<{
        id: string
        size: number
        mimeType: string
        fileName: string
        createdAt: string
        updatedAt: string
      }>
      appFileCount: number
    }
    variables: {
      offset: number
      limit: number
    }
  }
  tagRelationsGQL: {
    result: {
      tagRelations: Array<{
        tagId: string
        key: string
      }>
    }
    variables: {
      type: 'DEFAULT' | 'AUDIO' | 'VIDEO' | 'IMAGE' | 'SMS' | 'CONTACT' | 'NOTE' | 'FEED_ENTRY' | 'CALL' | 'PACKAGE' | 'FILE' | 'APP_FILE' | 'DOC'
      keys: Array<string>
    }
  }
  chatChannelsGQL: {
    result: {
      chatChannels: Array<Fragment_ChatChannelFragment>
    }
    variables: undefined
  }
  fileInfoGQL: {
    result: {
      fileInfo: {
        path: string
        updatedAt: string
        size: number
        data?: {
          width: number
          height: number
          location?: {
            latitude: number
            longitude: number
          }
        } | {
          durationMs: number
          width: number
          height: number
          location?: {
            latitude: number
            longitude: number
          }
        } | {
          durationMs: number
          location?: {
            latitude: number
            longitude: number
          }
        }
      }
    }
    variables: {
      path: string
      fileName: string
    }
  }
  smsGQL: {
    result: {
      sms: Array<Fragment_SmsFragment>
      smsCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  simsGQL: {
    result: {
      sims: Array<{
        id: string
        label: string
        number: string
        subscriptionId: number
      }>
    }
    variables: undefined
  }
  smsConversationsGQL: {
    result: {
      smsConversations: Array<Fragment_SmsConversationFragment>
      smsConversationCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  smsConversationsWithAddressesGQL: {
    result: {
      smsConversations: Array<Fragment_SmsConversationWithAddressesFragment>
      smsConversationCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  contactsGQL: {
    result: {
      contacts: Array<Fragment_ContactFragment>
      contactCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  contactSourcesGQL: {
    result: {
      contactSources: Array<{
        name: string
        type: string
      }>
    }
    variables: undefined
  }
  callsGQL: {
    result: {
      calls: Array<Fragment_CallFragment>
      callCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  imagesGQL: {
    result: {
      images: Array<Fragment_ImageFragment>
      imageCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
      sortBy: 'DATE_ASC' | 'DATE_DESC' | 'SIZE_ASC' | 'SIZE_DESC' | 'NAME_ASC' | 'NAME_DESC' | 'TAKEN_AT_DESC'
    }
  }
  imageSearchStatusGQL: {
    result: {
      imageSearchStatus: {
        status: 'UNAVAILABLE' | 'DOWNLOADING' | 'LOADING' | 'READY' | 'ERROR'
        downloadProgress: number
        errorMessage: string
        modelSize: number
        modelDir: string
        isIndexing: boolean
        totalImages: number
        indexedImages: number
      }
    }
    variables: undefined
  }
  scanProgressGQL: {
    result: {
      scanProgress: {
        indexed: number
        pending: number
        total: number
        state: 'IDLE' | 'RUNNING' | 'PAUSED' | 'STOPPED'
      }
    }
    variables: undefined
  }
  videosGQL: {
    result: {
      videos: Array<Fragment_VideoFragment>
      videoCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
      sortBy: 'DATE_ASC' | 'DATE_DESC' | 'SIZE_ASC' | 'SIZE_DESC' | 'NAME_ASC' | 'NAME_DESC' | 'TAKEN_AT_DESC'
    }
  }
  audiosGQL: {
    result: {
      items: Array<Fragment_AudioFragment>
      total: number
    }
    variables: {
      offset: number
      limit: number
      query: string
      sortBy: 'DATE_ASC' | 'DATE_DESC' | 'SIZE_ASC' | 'SIZE_DESC' | 'NAME_ASC' | 'NAME_DESC' | 'TAKEN_AT_DESC'
    }
  }
  filesGQL: {
    result: {
      files: Array<Fragment_FileFragment>
    }
    variables: {
      root: string
      offset: number
      limit: number
      query: string
      sortBy: 'DATE_ASC' | 'DATE_DESC' | 'SIZE_ASC' | 'SIZE_DESC' | 'NAME_ASC' | 'NAME_DESC' | 'TAKEN_AT_DESC'
    }
  }
  recentFilesGQL: {
    result: {
      recentFiles: Array<Fragment_FileFragment>
    }
    variables: undefined
  }
  mountsGQL: {
    result: {
      mounts: Array<{
        id: string
        name: string
        path: string
        mountPoint: string
        fsType: string
        totalBytes: number
        usedBytes: number
        freeBytes: number
        remote: boolean
        alias: string
        driveType: 'INTERNAL_STORAGE' | 'SDCARD' | 'USB_STORAGE' | 'APP'
        diskId: string
      }>
    }
    variables: undefined
  }
  disksGQL: {
    result: {
      disks: Array<{
        id: string
        name: string
        path: string
        sizeBytes: number
        removable: boolean
        model?: string
      }>
    }
    variables: undefined
  }
  nasMountsMetaGQL: {
    result: {
      mounts: Array<{
        id: string
        name: string
        alias: string
        label?: string
        mountPoint: string
        fsType: string
        totalBytes: number
        usedBytes: number
        freeBytes: number
        remote: boolean
        driveType: 'INTERNAL_STORAGE' | 'SDCARD' | 'USB_STORAGE' | 'APP'
        diskId: string
        path: string
        partitionNum?: number
        uuid?: string
      }>
    }
    variables: undefined
  }
  sambaSettingsGQL: {
    result: {
      sambaSettings: {
        enabled: boolean
        username: string
        hasPassword: boolean
        shares: Array<{
          name: string
          sharePath: string
          auth: 'GUEST' | 'PASSWORD'
          readOnly: boolean
        }>
        serviceName: string
        serviceActive: boolean
        serviceEnabled: boolean
      }
    }
    variables: undefined
  }
  favoriteFoldersGQL: {
    result: {
      favoriteFolders: Array<{
        rootPath: string
        fullPath: string
        alias?: string
      }>
    }
    variables: undefined
  }
  appGQL: {
    result: {
      app: Fragment_AppFragment
    }
    variables: undefined
  }
  audioQueueGQL: {
    result: {
      items: Array<Fragment_AudioItemFragment>
      total: number
      playback: {
        mode: 'REPEAT' | 'REPEAT_ONE' | 'SHUFFLE'
        currentPath?: string
        isPlaying: boolean
        positionMs: number
      }
    }
    variables: {
      offset: number
      limit: number
    }
  }
  tagsGQL: {
    result: {
      tags: Array<Fragment_TagFragment>
    }
    variables: {
      type: 'DEFAULT' | 'AUDIO' | 'VIDEO' | 'IMAGE' | 'SMS' | 'CONTACT' | 'NOTE' | 'FEED_ENTRY' | 'CALL' | 'PACKAGE' | 'FILE' | 'APP_FILE' | 'DOC'
    }
  }
  mediaBucketsGQL: {
    result: {
      mediaBuckets: Array<{
        id: string
        name: string
        itemCount: number
        topItemPaths: Array<string>
      }>
    }
    variables: {
      type: 'AUDIO' | 'VIDEO' | 'IMAGE' | 'DOC'
    }
  }
  notesGQL: {
    result: {
      notes: Array<{
        id: string
        title: string
        deletedAt?: string
        createdAt: string
        updatedAt: string
        tags: Array<Fragment_TagSubFragment>
      }>
      noteCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  noteGQL: {
    result: {
      note?: Fragment_NoteFragment
    }
    variables: {
      id: string
    }
  }
  feedsGQL: {
    result: {
      feeds: Array<Fragment_FeedFragment>
    }
    variables: undefined
  }
  feedEntriesGQL: {
    result: {
      items: Array<{
        id: string
        title: string
        url: string
        image: string
        author: string
        feedId: string
        rawId: string
        publishedAt: string
        createdAt: string
        updatedAt: string
        tags: Array<Fragment_TagSubFragment>
      }>
      total: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  feedsTagsGQL: {
    result: {
      tags: Array<Fragment_TagFragment>
      feeds: Array<Fragment_FeedFragment>
    }
    variables: {
      type: 'DEFAULT' | 'AUDIO' | 'VIDEO' | 'IMAGE' | 'SMS' | 'CONTACT' | 'NOTE' | 'FEED_ENTRY' | 'CALL' | 'PACKAGE' | 'FILE' | 'APP_FILE' | 'DOC'
    }
  }
  bucketsTagsGQL: {
    result: {
      tags: Array<Fragment_TagFragment>
      mediaBuckets: Array<{
        id: string
        name: string
        itemCount: number
        topItemPaths: Array<string>
      }>
    }
    variables: {
      type: 'AUDIO' | 'VIDEO' | 'IMAGE' | 'DOC'
      tagType: 'DEFAULT' | 'AUDIO' | 'VIDEO' | 'IMAGE' | 'SMS' | 'CONTACT' | 'NOTE' | 'FEED_ENTRY' | 'CALL' | 'PACKAGE' | 'FILE' | 'APP_FILE' | 'DOC'
    }
  }
  feedEntryGQL: {
    result: {
      feedEntry?: {
        feed?: Fragment_FeedFragment
      } & Fragment_FeedEntryFragment
    }
    variables: {
      id: string
    }
  }
  imageCountGQL: {
    result: {
      total: number
      trash: number
    }
    variables: {
      query: string
    }
  }
  audioCountGQL: {
    result: {
      total: number
      trash: number
    }
    variables: {
      query: string
    }
  }
  docsGQL: {
    result: {
      items: Array<Fragment_DocFragment>
      total: number
    }
    variables: {
      offset: number
      limit: number
      query: string
      sortBy: 'DATE_ASC' | 'DATE_DESC' | 'SIZE_ASC' | 'SIZE_DESC' | 'NAME_ASC' | 'NAME_DESC' | 'TAKEN_AT_DESC'
    }
  }
  docCountGQL: {
    result: {
      total: number
      trash: number
      extGroups: Array<{
        ext: string
        count: number
      }>
    }
    variables: {
      query: string
    }
  }
  videoCountGQL: {
    result: {
      total: number
      trash: number
    }
    variables: {
      query: string
    }
  }
  packageCountGQL: {
    result: {
      total: number
      system: number
    }
    variables: undefined
  }
  feedEntryCountGQL: {
    result: {
      total: number
      today: number
      feedEntryCounts: Array<{
        id: string
        count: number
      }>
    }
    variables: undefined
  }
  contactCountGQL: {
    result: {
      total: number
    }
    variables: undefined
  }
  callCountGQL: {
    result: {
      total: number
      incoming: number
      outgoing: number
      missed: number
    }
    variables: undefined
  }
  smsCountGQL: {
    result: {
      smsBoxCounts: {
        total: number
        inbox: number
        sent: number
        drafts: number
      }
    }
    variables: undefined
  }
  archivedSmsConversationsGQL: {
    result: {
      archivedSmsConversations: Array<Fragment_SmsConversationFragment>
    }
    variables: undefined
  }
  archivedSmsConversationsWithAddressesGQL: {
    result: {
      archivedSmsConversations: Array<Fragment_SmsConversationWithAddressesFragment>
    }
    variables: undefined
  }
  noteCountGQL: {
    result: {
      total: number
      trash: number
    }
    variables: undefined
  }
  packagesGQL: {
    result: {
      packages: Array<Fragment_PackageFragment>
      packageCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
      sortBy: 'DATE_ASC' | 'DATE_DESC' | 'SIZE_ASC' | 'SIZE_DESC' | 'NAME_ASC' | 'NAME_DESC' | 'TAKEN_AT_DESC'
    }
  }
  packageStatusesGQL: {
    result: {
      packageStatuses: Array<{
        id: string
        exists: boolean
        updatedAt?: string
      }>
    }
    variables: {
      ids: Array<string>
    }
  }
  isScreenMirroringGQL: {
    result: {
      isScreenMirroring: boolean
      screenMirrorControlEnabled: boolean
      screenMirrorQuality: {
        mode: 'HD' | 'SMOOTH'
        resolution: number
      }
    }
    variables: undefined
  }
  screenMirrorVideoCodecGQL: {
    result: {
      screenMirrorVideoCodec?: {
        annexB: string
        keyFrame?: string
      }
    }
    variables: undefined
  }
  screenMirrorControlEnabledGQL: {
    result: {
      screenMirrorControlEnabled: boolean
    }
    variables: undefined
  }
  screenMirrorQualityGQL: {
    result: {
      screenMirrorQuality: {
        mode: 'HD' | 'SMOOTH'
      }
    }
    variables: undefined
  }
  requestScreenMirrorKeyFrameGQL: {
    result: {
      requestScreenMirrorKeyFrame: boolean
    }
    variables: undefined
  }
  notificationsGQL: {
    result: {
      notifications: Array<Fragment_NotificationFragment>
    }
    variables: undefined
  }
  clipboardItemsGQL: {
    result: {
      clipboardItems: Array<Fragment_ClipboardItemFragment>
      clipboardItemCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  deviceInfoGQL: {
    result: {
      deviceInfo: Fragment_DeviceInfoFragment
      deviceStatus: Fragment_DeviceStatusFragment
    }
    variables: undefined
  }
  deviceStatusGQL: {
    result: {
      deviceStatus: {
        batteryLevel?: number
        charging: boolean
      }
    }
    variables: undefined
  }
  appLogsGQL: {
    result: {
      appLogs: Array<string>
    }
    variables: {
      offset: number
      limit: number
    }
  }
  appLogPathGQL: {
    result: {
      appLogPath: string
    }
    variables: undefined
  }
  dbPathGQL: {
    result: {
      dbPath: string
    }
    variables: undefined
  }
  dataStorePathGQL: {
    result: {
      dataStorePath: string
    }
    variables: undefined
  }
  uploadedChunksGQL: {
    result: {
      uploadedChunks: Array<string>
    }
    variables: {
      fileId: string
    }
  }
  mergeStatusGQL: {
    result: {
      mergeStatus: {
        status: 'NONE' | 'STARTED' | 'MERGING' | 'DONE' | 'FAILED'
        value?: string
        mergedSize?: number
        error?: string
      }
    }
    variables: {
      fileId: string
    }
  }
  pomodoroSettingsGQL: {
    result: {
      pomodoroSettings: {
        workDurationMin: number
        shortBreakDurationMin: number
        longBreakDurationMin: number
        pomodorosBeforeLongBreak: number
        showNotification: boolean
        playSoundOnComplete: boolean
      }
    }
    variables: undefined
  }
  pomodoroTodayAndSettingsGQL: {
    result: {
      pomodoroToday: {
        date: string
        completedCount: number
        currentRound: number
        timeLeftSec: number
        totalTimeSec: number
        isRunning: boolean
        isPaused: boolean
        state: 'WORK' | 'SHORT_BREAK' | 'LONG_BREAK'
      }
      pomodoroSettings: {
        workDurationMin: number
        shortBreakDurationMin: number
        longBreakDurationMin: number
        pomodorosBeforeLongBreak: number
        showNotification: boolean
        playSoundOnComplete: boolean
      }
    }
    variables: undefined
  }
  dataStoreEntriesGQL: {
    result: {
      dataStoreEntries: Array<{
        key: string
        value: string
      }>
    }
    variables: undefined
  }
  dbTablesGQL: {
    result: {
      dbTables: Array<string>
    }
    variables: undefined
  }
  dbTableRowCountGQL: {
    result: {
      dbTableRowCount: number
    }
    variables: {
      table: string
    }
  }
  dbTableRowsGQL: {
    result: {
      dbTableRows: Array<string>
    }
    variables: {
      table: string
      offset: number
      limit: number
    }
  }
  dbTableInfoGQL: {
    result: {
      dbTableInfo: {
        idKey: string
      }
    }
    variables: {
      table: string
    }
  }
  bookmarksGQL: {
    result: {
      bookmarks: Array<Fragment_BookmarkFragment>
      bookmarkGroups: Array<Fragment_BookmarkGroupFragment>
    }
    variables: undefined
  }
  isDiscoveringGQL: {
    result: {
      isDiscovering: boolean
    }
    variables: undefined
  }
  PEER_CLIPBOARD_GQL: {
    result: {
      clipboardItems: Array<Fragment_ClipboardItemFragment>
      clipboardItemCount: number
    }
    variables: {
      offset: number
      limit: number
      query: string
    }
  }
  PEER_NOTIFICATIONS_GQL: {
    result: {
      notifications: Array<Fragment_NotificationFragment>
      app: {
        permissions: Array<'WRITE_EXTERNAL_STORAGE' | 'READ_SMS' | 'SEND_SMS' | 'READ_CONTACTS' | 'WRITE_CONTACTS' | 'READ_CALL_LOG' | 'WRITE_CALL_LOG' | 'CALL_PHONE' | 'POST_NOTIFICATIONS' | 'NEARBY_WIFI_DEVICES' | 'ACCESS_FINE_LOCATION' | 'CAMERA' | 'SYSTEM_ALERT_WINDOW' | 'RECORD_AUDIO' | 'READ_MEDIA_IMAGES' | 'READ_MEDIA_VIDEOS' | 'READ_MEDIA_AUDIO' | 'NOTIFICATION_LISTENER' | 'READ_PHONE_STATE' | 'READ_PHONE_NUMBERS' | 'SCHEDULE_EXACT_ALARM' | 'QUERY_ALL_PACKAGES' | 'ADB' | 'CLIPBOARD'>
        urlToken: string
      }
    }
    variables: undefined
  }
  LIST_QUERY: {
    result: {
      imageEditorProjects: Array<{
        id: string
        thumbnail?: string
        canvasWidth: number
        canvasHeight: number
        layerCount: number
        updatedAt: string
      }>
    }
    variables: undefined
  }
  GET_QUERY: {
    result: {
      imageEditorProject?: {
        id: string
        stateB64: string
        thumbnail?: string
        canvasWidth: number
        canvasHeight: number
        layerCount: number
        updatedAt: string
      }
    }
    variables: {
      id: string
    }
  }
  SAVE_MUTATION: {
    result: {
      saveImageEditorProject: {
        id: string
      }
    }
    variables: {
      id: string
      input: unknown
    }
  }
  DELETE_MUTATION: {
    result: {
      deleteImageEditorProject: boolean
    }
    variables: {
      id: string
    }
  }
  decodeFrame: {
    result: {
      broadcastImageEditorUpdate: boolean
    }
    variables: {
      id: string
      update: string
    }
  }
  homeStatsGQL: {
    result: {
      audioCount: number
      imageCount: number
      videoCount: number
      docCount: number
      packageCount: number
      noteCount: number
      feedEntryCount: number
      smsCount: number
      callCount: number
      contactCount: number
      mounts: Array<{
        id: string
        path: string
        mountPoint: string
        totalBytes: number
        freeBytes: number
        driveType: 'INTERNAL_STORAGE' | 'SDCARD' | 'USB_STORAGE' | 'APP'
      }>
    }
    variables: {
      mediaQuery: string
    }
  }
}
